### ISSUE TITLE
Highlight advantages in graphs & charts

### ISSUE THREAD

**Issue by sminke** [autorivalry/ar-admin#82] opened 2016-01-15 17:11 UTC
As a user, i want a way to highlight the metrics in the charts/graphs that show the "hero" vehicle with an advantage over the villain.

**Comment by sminke** [comment] 2016-01-15 17:11
@jordanskole

**Comment by jordanskole** [comment] 2016-01-15 20:01
@sminke :boom: nice work :+1: 
- Nice work phrasing the issue as a user story, next time try and get it in the title though. You can edit the title directly on GitHub, but I haven't covered that yet. Bonus if you figure it out on your own. 
- Keep in mind there are many types of "users" so try and avoid using just "user." for example this title could be re-written "As a **consumer** I want an easy way to which features the hero outperforms the villain."
- This issue probably relates to [ar-render](https://waffle.io/autorivalry/ar-render) and not [ar-admin](https://waffle.io/autorivalry/ar-admin) but I didn't cover that yet, and the distinctions is confusing right now.

**Comment by jordanskole** [comment] 2016-01-15 21:37
Closing, duplicate of [ar-render #21](https://github.com/autorivalry/ar-render/issues/21)

**Closed as completed by jordanskole** 2016-01-15 21:37 UTC
